site_name: OCR
site_description: OCR Documentation
site_author: Nivratti Boyane

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: amber
  highlightjs: true

nav:
  - index.md
  - installation.md
  - dataset_preparation:
    - dataset_preparation/annotation-tool.md
    - dataset_preparation/paddleocr_dataset_format.md
  - training:
    - training/recognition_paddleocr.md

  - structured_data.md

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_div_format ''
  - pymdownx.tabbed
  
  - pymdownx.inlinehilite
  - pymdownx.snippets
  
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js

extra:
  generator: false